### ISSUE TITLE
Environments are not set when local invoke

### ISSUE THREAD

**Issue by jmonsma** [CruGlobal/serverless-merge-config#3]
So I'm having troubles with environment variables that are not set when local invoking the lambda function.
The environments set in the env.yml are not found when local invoking it. 
Deploying the function to aws the environments vars are set with correct values.
Below example of the serverless.yml and env.yml
In the local invoke, when i log the process.env only `VAR` is found. When deploying it both `VAR` and `VERSION` are found. When i log the `this.serverless.service` after the deepmerge on `before:invoke:local:invoke` i can see the var is set there, but they dont show up in the process.env
Im using version 1.1.0 

serverless.yml
```
service: test

plugins:
  - '@cruglobal/serverless-merge-config'
  - serverless-plugin-scripts
  - serverless-webpack

package:
  individually: true
...
provider:
  name: aws
  runtime: nodejs8.10
  environment:
    VAR: '12345'
    $<<: ${file(../../env.yml)}
...
```

env.yml
```
VERSION: '1.0'
```
