### ISSUE TITLE
What's the merging precedence?

### ISSUE THREAD

**Issue by MaG21** [CruGlobal/serverless-merge-config#7]
I'm wondering what's the order of the merging operation as in, when will a value take precedence over other for example (simplified):

```yaml
#defaults.yml
key: "akey"
secret: "asecret"
```

```yaml
custom:
    $<<: ${file:defaults.yml}
    key: "myKey",
    secret: "mySecret"
 ```

What will be the value of key after the merge, `myKey` or `akey` ?
